services:
  guacd:
    container_name: guacd
    image: guacamole/guacd:latest
    restart: unless-stopped
    networks:
      - guac_network

  postgres:
    container_name: postgres_guac
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      # SANS "QL" POUR LA BASE DE DONNEES
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: GuacamoleTest2024
      POSTGRES_DB: guacamole_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guac_network

  guacamole:
    container_name: guacamole_web
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      # AVEC "QL" POUR GUACAMOLE !
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: GuacamoleTest2024
    depends_on:
      - guacd
      - postgres
    networks:
      - guac_network

networks:
  guac_network:
    driver: bridge

volumes:
  postgr
